-- Harness selftest: IFS path expansion via qsh ($HOME) for RUNSQLSTM SRCSTMF.
-- Unqualified names resolve through DFTRDBCOL (set by the manifest).
CREATE OR REPLACE TABLE VFYIFS (TAG VARCHAR(30), VAL VARCHAR(100));
INSERT INTO VFYIFS VALUES ('IFS-SELFTEST', 'ok');
INSERT INTO VFYIFS SELECT 'CURRENT-SCHEMA', CURRENT SCHEMA FROM SYSIBM.SYSDUMMY1;
INSERT INTO VFYIFS SELECT 'JT-DOLLAR-BRACKET', CAST(K AS VARCHAR(10))
  FROM JSON_TABLE('{"a":[{"k":1},{"k":2}]}', 'lax $.a[*]'
       COLUMNS(K INT PATH 'lax $.k')) AS T;
