blank_issues_enabled: true
contact_links:
  - name: 貢献の全般的なルール
    url: https://github.com/bluemoonjp/scratchpad-ibmi-learning-from-zero/blob/main/CONTRIBUTING.md
    about: Issue を出す前に、まず CONTRIBUTING.md を確認してください。
